name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creating artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "${{ secrets.ENV_FILE_COOFFEH }}" > whiskyh/.env
          echo "${{ secrets.ENV_FILE_WHISKYH }}" > cooffeh/.env
          cd cooffeh
          rm -rf Tests git* .git* \
              devreqs.txt .env.example \
              Dockerfile docker-compose.yml \
              /tmp/*.tar.gz
          cd ..
          touch "${GITHUB_SHA}".tar.gz
          tar -czf "${GITHUB_SHA}".tar.gz --exclude="${GITHUB_SHA}".tar.gz .
      - name: Storing artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: app-build
      - name: Uploading to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          source: ${{ github.sha }}.tar.gz
          target: /tmp/
      - name: Extracting files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            rm -rf /home/bots
            mkdir /home/bots
            tar -xzf /tmp/${{ github.sha }}.tar.gz -C /home/bots
            python3.11 -m venv venv
            source venv/bin/activate
            pip install -r reqs.txt
